spring.application.name=SmartLabBackend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smartlab}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret.key=${JWT_SECRET:smartlab-local-dev-secret-key-32-bytes-minimum}

server.servlet.context-path=/api/v1.0
smartlab.openapi.server-url=http://localhost:8080/api/v1.0
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs

smartlab.invite.ttl-hours=72
smartlab.frontend.base-url=${FRONTEND_BASE_URL:http://127.0.0.1:5173}
smartlab.session.max-active=3
smartlab.session.ttl-days=30



#Email configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a0d5da001@smtp-brevo.com
spring.mail.password=xsmtpsib-dbaf090c72b3026cd53c098b58b6e7c071fe11bf0b96c6a531bde8559bab82c8-SH6ygS1oxJ6xpX6Y
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=tdgaming090@gmail.com
